# Generated by Django 3.0.7 on 2020-06-26 03:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('descricao_produto', models.TextField(max_length=100)),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('imagem_produto', models.ImageField(blank=True, null=True, upload_to='img')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', max_length=10)),
                ('data_publicacao', models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 26, 0, 47, 30, 217188))),
                ('publicado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Categoria')),
            ],
        ),
    ]
