# Generated by Django 3.0.7 on 2020-06-29 13:36

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20200627_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 29, 10, 36, 48, 912103)),
        ),
    ]
