# Generated by Django 3.0.7 on 2020-06-29 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20200629_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='data_envio',
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 29, 14, 21, 47, 932979)),
        ),
    ]
