# Generated by Django 3.0.7 on 2020-06-29 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20200629_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='data_envio',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 29, 15, 8, 16, 844471)),
        ),
    ]
