# Generated by Django 3.0.7 on 2020-06-29 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_auto_20200629_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='email_contato',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='data_envio',
            new_name='enviado_em',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='mensagem_contato',
            new_name='mensagem',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='nome_contato',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 29, 18, 34, 20, 494999)),
        ),
    ]
