# Generated by Django 3.0.7 on 2020-07-03 02:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0007_auto_20200629_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='assunto',
            field=models.CharField(choices=[('sugestao', 'Sugestão'), ('reclamacao', 'Reclamação')], default='sugestao', max_length=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 2, 23, 22, 27, 441212)),
        ),
    ]
