# Generated by Django 3.0.7 on 2020-07-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_auto_20200702_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data_criacao',
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
